name: 'Github Action Notify Release'
description: 'Create an issue if there is a release pending'
inputs:
  github-token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
  notify-after:
    description: 'The time after which unreleased commits should be considered stale and should notify for a release'
    required: false
  stale-days:
    description: 'Number of days of inactivity before a release becomes stale'
    required: false
    default: 7
  commit-messages-lines:
    description: 'Limit the number of first x lines from commit messages that will be added in the issue description. No truncation when set to 0.'
    required: false
    default: 1
# runs:
#   using: 'node16'
#   main: 'dist/index.js'

runs:
  using: 'composite'
  steps:
    - name: Checkout the fresh project
      uses: actions/checkout@v3

    - name: Configure git
      run: |
        git config --global user.email "${{ inputs.actor-email }}"
        git config --global user.name "${{ inputs.actor-name }}"
      shell: 'bash'

    - name: Do the fun stuff
      uses: actions/github-script@v6
      with:
        script: |
          const script = require("./dist/index.js")
