name: 'Github Action Notify Release'
description: 'Create an issue if there is a release pending'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  stale-days:
    description: 'Number of days of inactivity before a release becomes stale'
    required: false
    default: 7
runs:
  using: 'node12'
  main: 'dist/index.js'
