name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Run CI, Eslint and tests
        run: npm ci
        run: npm run lint
        run: npm test