name: notify-release
on:
  workflow_dispatch:
    branches:
      - main
  release:
    types: [published]
  issues:
    types: [closed]
  schedule:
    - cron: '30 8 * * *'
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check if there's a release pending
        id: notify
        uses: nearform-actions/github-action-notify-release@main
        with:
          notify-after: '0'
